
// Copyright (c) 2017 Mark A. Olbert some rights reserved
//
// This software is licensed under the terms of the MIT License
// (https://opensource.org/licenses/MIT)

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Xml.Linq;
using Microsoft.Tools.WindowsInstallerXml.Bootstrapper;
using Serilog;

namespace Olbert.Wix
{
    /// <summary>
    /// Defines the properties of a Wix bundle, and provides a method for loading them
    /// from an Xml file generated by the Wix Toolset.
    /// </summary>
    public class WixBundleProperties
    {
        /// <summary>
        /// The file name stub of the Xml file generated by the Wix Toolset containing information
        /// about the active Wix bundle.
        /// </summary>
        public const string BootstrapperAppDataName = "BootstrapperApplicationData";

        /// <summary>
        /// The Wix bundle's Xml namespace
        /// </summary>
        public static XNamespace ManifestNamespace =
            "http://schemas.microsoft.com/wix/2010/BootstrapperApplicationData";

        /// <summary>
        /// Parses a Wix Toolset bundle Xml file
        /// </summary>
        /// <param name="xmlPath">the path to the folder where the Wix Toolset Xml bundlefile is located.
        /// If not specified, the folder where the app is stored is used.</param>
        /// <param name="logger">an optional Serilog logger</param>
        /// <returns>the Wix Toolset bundle, as xml, or null if the file to parse could not be found
        /// or a problem occurred</returns>
        public static XElement GetAppXml( string xmlPath = null, ILogger logger = null )
        {
            if( String.IsNullOrEmpty( xmlPath ) )
            {
                logger?.Information( $"checking default location for {BootstrapperAppDataName}.xml file" );

                var workingFolder = Path.GetDirectoryName( typeof(WixBundleProperties).Assembly.Location );

                if( workingFolder == null )
                {
                    logger?.Error( "couldn't find default assembly location" );
                    return null;
                }

                xmlPath = Path.Combine( workingFolder, $"{BootstrapperAppDataName}.xml" );
                logger?.Information( $"{BootstrapperAppDataName}.xml file found at {xmlPath}" );
            }

            XElement retVal = null;

            try
            {
                using( var reader = new StreamReader( xmlPath ) )
                {
                    var xml = reader.ReadToEnd();
                    var xDoc = XDocument.Parse( xml );

                    retVal = xDoc.Element( ManifestNamespace + BootstrapperAppDataName );
                    logger?.Information( $"parsed {BootstrapperAppDataName}.xml file" );
                }
            }
            catch( Exception e )
            {
                logger?.Error( e, "Failed to parse " + BootstrapperAppDataName + ".xml file; message was {Exception}" );
            }

            return retVal;
        }

        /// <summary>
        /// Creates a WixBundleProperties object by loading the Wix Toolset Xml bundle file and
        /// parsing it.
        /// </summary>
        /// <param name="xmlPath">the path to the folder where the Wix Toolset Xml bundlefile is located.
        /// If not specified, the folder where the app is stored is used.</param>
        /// <param name="logger">an optional Serilog logger</param>
        /// <returns>a WixBundleProperties object</returns>
        public static WixBundleProperties Load( string xmlPath = null, ILogger logger = null )
        {
            var xml = GetAppXml( xmlPath );
            if( xml == null ) return null;

            var xBundleProp = xml.Element( ManifestNamespace + nameof(WixBundleProperties) );
            if( xBundleProp == null )
            {
                logger?.Error( $"Couldn't find WixBundleProperties element in {BootstrapperAppDataName}.xml file" );
                return null;
            }

            WixBundleProperties retVal = new WixBundleProperties()
            {
                DisplayName = xBundleProp.GetAttribute<string>( "DisplayName" ),
                LogPathVariable = xBundleProp.GetAttribute<string>( "LogPathVariable" ),
                Compressed = xBundleProp.GetAttribute<bool>("Compressed"),
                Id = xBundleProp.GetAttribute<string>("Id"),
                UpgradeCode = xBundleProp.GetAttribute<Guid>("UpgradeCode"),
                PerMachine = xBundleProp.GetAttribute<bool>("PerMachine")
            };

            retVal.Prerequisites.AddRange( xml.Descendants( ManifestNamespace + nameof(WixMbaPrereqInformation) )
                .Select( pri => new WixMbaPrereqInformation()
                {
                    LicenseUrl = pri.GetAttribute<string>("LicenseUrl"),
                    PackageID = pri.GetAttribute<string>("PackageId")
                } ) );

            retVal.Packages.AddRange( xml.Descendants( ManifestNamespace + nameof(WixPackageProperties))
                .Select( pp => new WixPackageProperties()
                {
                    Package = pp.GetAttribute<string>( "Package" ),
                    Vital = pp.GetAttribute<bool>( "Vital" ),
                    DisplayName = pp.GetAttribute<string>( "DisplayName" ),
                    Description = pp.GetAttribute<string>( "Description" ),
                    DownloadSize = pp.GetAttribute<long>( "DownloadSize" ),
                    PackageSize = pp.GetAttribute<long>( "PackageSize" ),
                    InstalledSize = pp.GetAttribute<long>( "InstalledSize" ),
                    PackageType = pp.GetAttribute<PackageType>( "PackageType" ),
                    Permanent = pp.GetAttribute<bool>( "Permanent" ),
                    LogPathVariable = pp.GetAttribute<string>( "LogPathVariable" ),
                    RollbackLogPathVariable = pp.GetAttribute<string>( "RollbackLogPathVariable" ),
                    Compressed = pp.GetAttribute<bool>( "Compressed" ),
                    DisplayInternalUI = pp.GetAttribute<bool>( "DisplayInternalUI" ),
                    ProductCode = pp.GetAttribute<Guid>( "ProductCode" ),
                    UpgradeCode = pp.GetAttribute<Guid>( "UpgradeCode" ),
                    Version = pp.GetAttribute<Version>( "Version" ),
                    InstallCondition = pp.GetAttribute<string>( "InstallCondition" ),
                    Cache = pp.GetAttribute<YesNoAlways>( "Cache" )
                } ) );

            retVal.Prerequisites.ForEach( pr => pr.Properties =
                retVal.Packages
                    .SingleOrDefault(pkg => pkg.Package.Equals( pr.PackageID, StringComparison.OrdinalIgnoreCase )) );

            List<WixPackageFeatureInfo> features = xml.Descendants( ManifestNamespace + nameof(WixPackageFeatureInfo) )
                .Select( pfi => new WixPackageFeatureInfo()
                {
                    Attributes = pfi.GetAttribute<int>( "Attributes" ),
                    Description = pfi.GetAttribute<string>( "Description" ),
                    Directory = pfi.GetAttribute<string>( "Directory" ),
                    Display = pfi.GetAttribute<Display>( "Display" ),
                    Feature = pfi.GetAttribute<string>( "Feature" ),
                    Level = pfi.GetAttribute<int>( "Level" ),
                    Size = pfi.GetAttribute<long>( "Size" ),
                    Title = pfi.GetAttribute<string>( "Title" ),
                    PackageID = pfi.GetAttribute<string>( "Package" ),
                    Parent = pfi.GetAttribute<string>( "Parent" )
                } )
                .ToList();

            features.ForEach( pfi =>
            {
                var pkg = retVal.Packages.SingleOrDefault(
                    x => x.Package.Equals( pfi.PackageID, StringComparison.OrdinalIgnoreCase ) );

                if( pkg == null )
                    logger?.Error( $"Couldn't find package '{pfi.PackageID}' for feature '{pfi.Feature}'" );
                else pkg.Features.Add( pfi );
            } );

            int lastChildCount = -1;
            int repeats = 0;

            while( true )
            {
                var childFeatures = features.Where( f => !String.IsNullOrEmpty( f.Parent ) ).ToList();

                var curChildren = childFeatures.Count;
                if( curChildren == 0 ) break;

                if( curChildren == lastChildCount ) repeats++;
                else repeats = 0;

                if( repeats > 10 )
                {
                    logger?.Error($"Exceeded 10 loops trying to assign child features to parents; aborting assignment");
                    break;
                }

                childFeatures.ForEach( cf =>
                {
                    var parentFeature =
                        features.SingleOrDefault(
                            f => f.Feature.Equals( cf.Parent, StringComparison.OrdinalIgnoreCase ) );

                    if( parentFeature == null )
                        logger?.Error(
                            $"Couldn't find parent feature '{cf.Parent}' for child feature '{cf.PackageID}'" );
                    else
                    {
                        cf.ParentFeature = parentFeature;
                        parentFeature.Features.Add( cf );
                    }
                });
            }

            return retVal;
        }

        /// <summary>
        /// The bundle's display name
        /// </summary>
        public string DisplayName { get; set; }

        /// <summary>
        /// TBD
        /// </summary>
        public string LogPathVariable { get; set; }

        /// <summary>
        /// TBD
        /// </summary>
        public bool Compressed { get; set; }

        /// <summary>
        /// The bundle's Wix ID
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// TBD
        /// </summary>
        public Guid UpgradeCode { get; set; }

        /// <summary>
        /// Flag indicating whether the install is per user (false) or per machine (true)
        /// </summary>
        public bool PerMachine { get; set; }

        /// <summary>
        /// The list of prerequisites required for the installation to proceed
        /// </summary>
        public List<WixMbaPrereqInformation> Prerequisites { get; } = new List<WixMbaPrereqInformation>();

        /// <summary>
        /// The list of packages to be installed
        /// </summary>
        public List<WixPackageProperties> Packages { get; } = new List<WixPackageProperties>();

        /// <summary>
        /// The number of packages which need to be installed (i.e., the number not present in the
        /// right version on the system)
        /// </summary>
        /// <returns>the number of packages which need to be installed</returns>
        public int GetNumPackagesToInstall()
        {
            return Packages
                .Where( pkg => !Prerequisites.Any(
                    pr => pr.PackageID.Equals( pkg.Package, StringComparison.OrdinalIgnoreCase ) ) )
                .Count( pkg =>
                    pkg.PackageState == PackageState.Absent
                    || pkg.PackageState == PackageState.Obsolete
                    || pkg.PackageState == PackageState.Superseded );
        }
    }
}
